Add DNS support to initrd

diff --git a/initramfs-tools/hooks/customize-image b/initramfs-tools/hooks/customize-image
--- a/initramfs-tools/hooks/customize-image
+++ b/initramfs-tools/hooks/customize-image
@@ -16,8 +16,9 @@ esac
 
 mkdir -p ${DESTDIR}/var/run/lldpd
 
-cp -v etc/*        ${DESTDIR}/etc
-cp -v register     ${DESTDIR}/bin
+cp -v etc/*             ${DESTDIR}/etc
+cp -v register          ${DESTDIR}/bin
+cp -v /etc/resolv.conf  ${DESTDIR}/etc
 
 for b in curl lshw lldpd lldpctl
 do
@@ -25,12 +26,14 @@ do
 done
 
 # copied from hooks/mountall
-libnss_files=`dpkg -L libc6 | grep libnss_files.so.2`
-if [ -f $libnss_files ]; then
-  cp -uv $libnss_files ${DESTDIR}/lib/libnss_files.so.2
-else
-  echo "libnss_files.so.2 not found"
-  echo "warning: mountall would not be able to connect to upstart"
-  exit 1
-fi
-
+for file in libnss_files.so.2 libnss_dns.so.2
+do
+  f=`dpkg -L libc6 | grep $file`
+  if [ -f $f ]; then
+    cp -uv $f ${DESTDIR}/lib/$file
+  else
+    echo "$file not found"
+    echo "warning: mountall would not be able to connect to upstart"
+    exit 1
+  fi
+done
